# Generated by Django 2.2 on 2022-03-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='oldprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
