# Generated by Django 2.2 on 2022-03-28 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_oldprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='oldprice',
            new_name='old_price',
        ),
    ]
