# Generated by Django 2.2 on 2022-03-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220328_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
