# Generated by Django 2.2 on 2022-03-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
    ]
